# 项目基础配置
project:
  name: "pattern-transform"
  version: "0.1.0"
  description: "Transform carpet effect images to flat patterns"

# 系统配置
system:
  device: "cpu"
  num_workers: 1
  seed: 42

# 模型配置
model:
  name: "PatternTransformerV4"
  pretrained: true
  encoder: "resnet18"
  feature_dim: 64
  use_lightweight: true
  transformer:
    dim: 64
    num_heads: 4
    dim_feedforward: 256
    dropout: 0.2
    batch_first: true
  
  # 3D特征处理配置
  depth_module:
    enabled: true
    attention_reduction: 16
    use_residual: true
  
  # 空间变换配置
  spatial_transformer:
    enabled: true
    multi_scale: true
    kernel_sizes: [3, 5]
    use_attention: true
  
  feature_fusion:
    clip_feature_dim: 64
    original_feature_dim: 64
    fusion_dim: 64
    dropout_rate: 0.2

# 训练配置
train:
  batch_size: 1
  epochs: 50
  learning_rate: 0.0005
  save_interval: 5
  val_interval: 2
  
  # 优化器配置
  optimizer:
    type: 'adam'
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.01
    lr: 0.0005

  # 学习率调度器
  scheduler:
    type: 'cosine'
    params:
      T_max: 50
      eta_min: 0.000001

  # 早停配置
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001

  # 损失函数权重
  loss_weights:
    l1: 10.0
    perceptual: 1.0
    style: 1.0

  # 训练监控
  monitor:
    enabled: true
    log_interval: 10
    save_images: true
    num_samples: 4

# 数据配置
data:
  raw_dir: 'data/raw'
  processed_dir: 'data/processed'
  split_dir: 'data/split'
  input_size: [256, 256]
  batch_size: 1
  num_workers: 1
  augmentation:
    enabled: true
    rotation_limit: 15
    brightness_contrast_limit: 0.2
    hue_saturation_limit: 0.2
    noise_prob: 0.3
    blur_prob: 0.3
    flip_prob: 0.5

# 输出配置
output:
  save_dir: "outputs"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

# 损失函数配置
loss:
  lambda_l1: 0.4
  lambda_perceptual: 0.7
  lambda_style: 0.8
  lambda_ssim: 0.15
  lambda_depth: 0.2
  lambda_frequency: 0.5
  vgg_layers: [3, 8, 15]
  perceptual_weights: [1.0, 1.0, 1.0]

# 报告配置
report:
  formats:
    - html
    - markdown
    - pdf
    - notebook
  
  sections:
    - training_summary
    - performance_metrics
    - visualizations
    - recommendations
  
  visualization:
    include_loss_curves: true
    include_lr_curves: true
    include_predictions: true
    include_attention_maps: true

# 可视化配置
visualization:
  save_dir: 'runs'
  viz_interval: 2
  save_attention_maps: false
  plot_predictions: true
  save_interval: 200
  gif_fps: 10
  gif_quality: 90
  save_gifs: false

openai:
  api_key: ${OPENAI_API_KEY}
  
training:
  analysis_frequency: 200  # 每200个batch分析一次
  min_analysis_interval: 60  # 最小分析间隔60秒
  reference_generation: true
  quality_threshold: 7.0  # 质量分数阈值

debug:
  save_images: false  # 设置为true时保存生成的图像
  check_augmentation: true  # 是否在训练前检查数据增强效果
paths:
  output_dir: outputs  # 生成图像的保存目录

# 评估配置
evaluation:
  enabled_metrics:
    psnr: true
    ssim: true
    lpips: true
    edge_accuracy: true
    pattern_consistency: true
    perceptual_quality: true

# 训练配置
training:
  checkpoint:
    save_dir: "checkpoints"
    save_interval: 10
    keep_last: 2
    save_best: true
    save_latest: true
  
  analysis:
    frequency: 400
    min_interval: 120
    reference_generation: false
    quality_threshold: 7.0