# 项目基础配置
project:
  name: "pattern-transform"
  version: "0.1.0"
  description: "Transform carpet effect images to flat patterns"

# 系统配置
system:
  device: "mps"
  num_workers: 2
  seed: 42

# 模型配置
model:
  name: "PatternNet"
  pretrained: true
  encoder: "resnet18"
  feature_dim: 512
  use_lightweight: true
  transformer:
    dim: 256
    num_heads: 8
    dim_feedforward: 2048
    dropout: 0.1
    batch_first: true

# 训练配置
train:
  batch_size: 1
  epochs: 100
  learning_rate: 0.001
  save_interval: 10
  val_interval: 5
  
  # 优化器配置
  optimizer:
    type: 'adam'
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.01
    lr: 0.001

  # 学习率调度器
  scheduler:
    type: 'cosine'
    params:
      # Step LR 参数
      step_size: 30
      gamma: 0.1
      # Cosine LR 参数
      T_max: 100
      eta_min: 0.000001
      # ReduceLROnPlateau 参数
      factor: 0.1
      patience: 10
      min_lr: 0.000001
      mode: 'min'

  # 早停配置
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
    verbose: true

  # 梯度裁剪配置
  max_grad_norm: 1.0  # 最大梯度范数
  grad_logging:
    enabled: true
    frequency: 10  # 每多少个batch记录一次梯度信息

  loss_weights:
    l1_loss: 1.0
    perceptual_loss: 0.1
    # 添加其他损失项的权重

# 数据配置
data:
  input_size: [640, 640]
  augmentation:
    enabled: true
    prob: 0.8
    color_jitter:
      brightness: 0.1
      contrast: 0.1
      saturation: 0.1
      hue: 0.05
    affine:
      degrees: 15
      translate: [0.1, 0.1]
      scale: [0.9, 1.1]
      shear: 5
  train_ratio: 0.8
  raw_dir: "data/raw"
  batch_size: 1
  num_workers: 2

# 输出配置
output:
  save_dir: "outputs"
  checkpoint_dir: "checkpoints"
  log_dir: "logs"

# 损失函数配置
loss:
  lambda_l1: 1.0
  lambda_perceptual: 0.1
  lambda_style: 0.5
  lambda_ssim: 0.3
  vgg_layers: [3, 8, 15, 22]
  perceptual_weights: [1.0, 1.0, 1.0, 1.0]

# 报告配置
report:
  formats:
    - html
    - markdown
    - pdf
    - notebook
  
  sections:
    - training_summary
    - performance_metrics
    - visualizations
    - recommendations
  
  visualization:
    include_loss_curves: true
    include_lr_curves: true
    include_predictions: true
    include_attention_maps: true

# 可视化配置
visualization:
  save_dir: 'runs'
  viz_interval: 1
  save_attention_maps: true
  plot_predictions: true
  save_interval: 100  # 每隔多少个batch保存一次图像
  gif_fps: 10        # GIF帧率
  gif_quality: 95    # GIF质量
  save_gifs: true    # 是否保存GIF

openai:
  api_key: ${OPENAI_API_KEY}
  
training:
  analysis_frequency: 200  # 每200个batch分析一次
  min_analysis_interval: 60  # 最小分析间隔60秒
  reference_generation: true
  quality_threshold: 7.0  # 质量分数阈值

debug:
  save_images: false  # 设置为true时保存生成的图像
paths:
  output_dir: outputs  # 生成图像的保存目录